FROM mysql

ENV MYSQL_USER=taejun
ENV MYSQL_PASSWORD=12345678
ENV MYSQL_ROOT_PASSWORD=12345678
ENV MYSQL_DATABASE=docker_test 

CMD ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]